### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by benogle** [guileen/terminal-status#39]
_From @ST3tter on December 11, 2014 19:52_

Uncaught SyntaxError: Unexpected end of input

**Atom Version**: 0.154.0
**System**: Mac OS X 10.10
**Thrown From**: [terminal-status](https://github.com/guileen/terminal-status) package
### Steps To Reproduce
1. ...
2. ...
### Stack Trace

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html?loadSettings=%7B%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.154.0%22%2C%22shellLoadTime%22%3A247%7D:0

SyntaxError: Unexpected end of input
  at Object.parse (native)
  at /Users/tobiasmeerstetter/.atom/packages/terminal-status/lib/command-output-view.coffee:38:26
  at ChildProcess.exithandler (child_process.js:752:5)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:107:17)
  at Pipe.close (net.js:461:12)

```

_Copied from original issue: atom/atom#4559_

**Comment by dinosaurfiles** [comment]
+1

**Comment by superscott** [comment]
+1

**Comment by juunas11** [comment]
+1, Atom 0.179.0, Windows 7 32-bit
