### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by raysarebest** [guileen/terminal-status#40]
[Enter steps to reproduce below:]

Occurs on Atom startup

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.2
**Thrown From**: [terminal-status](https://github.com/guileen/terminal-status) package, v1.3.5
### Stack Trace

Uncaught SyntaxError: Unexpected end of input

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html?loadSettings=%7B%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.165.0%22%2C%22shellLoadTime%22%3A16494%7D:0

SyntaxError: Unexpected end of input
  at Object.parse (native)
  at /Users/michael/.atom/packages/terminal-status/lib/command-output-view.coffee:38:26
  at ChildProcess.exithandler (child_process.js:752:5)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:107:17)
  at Pipe.close (net.js:461:12)

```
### Commands

```
```
### Config

```
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "linter-jscs",
      "term",
      "term"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autoclose-html, v0.13.0
autocomplete-emojis, v0.6.0
autocomplete-paths, v0.9.0
autocomplete-plus, v1.0.0
autocomplete-snippets, v0.3.1
color-picker, v1.2.6
command-logger, v0.20.0
compass, v0.7.5
editor-stats, v0.16.0
git-log, v0.2.0
html-entities, v0.2.0
html-id-class-snippets, v1.4.1
linter, v0.9.0
linter-clang, v2.9.0
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-php, v0.0.11
linter-ruby, v0.1.4
linter-shellcheck, v0.0.6
linter-xmllint, v0.0.5
playlist, v0.1.7
terminal-status, v1.3.5
the-closer, v0.2.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by ahutatatong** [comment]
same problem, windows 7

**Comment by RightL** [comment]
Also on ubuntu

**Comment by pandres95** [comment]
It happens because the process environment is created from executing a series of commands, so if there's a missing command (usually `node`), output will be `undefined` or even garbage.
I'm working on this. For now, in Unix systems, there's a workaround: symbolic linking `nodejs` to `node`. I can't really know if this works on Windows, so I recommend @ahutatatong to get me know that.

**Comment by bambanx** [comment]
same on windows 8.1

**Comment by englercj** [comment]
+1 This is causing problems for me as well.

**Comment by DadaMonad** [comment]
how can I find out which command is missing?

**Comment by nikswamy** [comment]
+1 ... any progress on a fix for windows? Thanks!

**Comment by pandres95** [comment]
Please upgrade to test fix over `terminal-status@1.6.5`
