### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Vargash** [guileen/terminal-status#65]
[Enter steps to reproduce below:]

1. simply tried to open a new terminal from the Command Palette > Terminal Status: New

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [terminal-status](https://github.com/guileen/terminal-status) package, v1.6.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/vargash/.atom/packages/terminal-status/lib/cli-status-view.coffee:16

TypeError: undefined is not a function
  at atom-workspace.<anonymous> (/Users/vargash/.atom/packages/terminal-status/lib/cli-status-view.coffee:16:68)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:12.3 window:toggle-full-screen (atom-text-editor.editor)
     -0:10.5 project-manager:toggle (atom-text-editor.editor)
     -0:09.8 core:confirm (atom-text-editor.editor.mini)
     -0:03.5 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:01.4 core:move-down (atom-text-editor.editor.mini)
     -0:01.2 core:move-up (atom-text-editor.editor.mini)
     -0:01.1 core:confirm (atom-text-editor.editor.mini)
     -0:01.1 terminal-status:new (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v1.5.0
file-icons, v1.5.2
linter, v0.12.0
linter-csslint, v0.0.11
linter-jshint, v0.1.0
project-manager, v1.15.5
terminal-status, v1.6.0

# Dev
No dev packages
```

**Comment by ferryphang** [comment]
I got the same error too

**Comment by detj** [comment]
:+1: Getting this error

**Comment by hackerone** [comment]
why is this error closed? is it resolved?

**Comment by pandres95** [comment]
It is. Please upgrade to latest version (terminal-status@1.6.4) to get this issue solved.
