### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/Users/xxx/.zlogin'

### ISSUE THREAD

**Issue by Tedko** [guileen/terminal-status#67]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [terminal-status](https://github.com/guileen/terminal-status) package, v1.6.3

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/yanhan/.zlogin'

```
At fs.js:846

Error: ENOENT: no such file or directory, stat '/Users/yanhan/.zlogin'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at CommandOutputView.module.exports.CommandOutputView._fileInfoHtml (/Users/yanhan/.atom/packages/terminal-status/lib/command-output-view.coffee:161:17)
  at /Users/yanhan/.atom/packages/terminal-status/lib/command-output-view.coffee:141:25
  at Array.forEach (native)
  at CommandOutputView.module.exports.CommandOutputView.ls (/Users/yanhan/.atom/packages/terminal-status/lib/command-output-view.coffee:140:11)
  at CommandOutputView.module.exports.CommandOutputView.readLine (/Users/yanhan/.atom/packages/terminal-status/lib/command-output-view.coffee:60:15)
  at atom-workspace.<anonymous> (/Users/yanhan/.atom/packages/terminal-status/lib/command-output-view.coffee:42:61)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:521:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
  4x -0:10.4 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "color-gutter",
      "sublime-tabs",
      "vim-mode",
      "linter-htmlhint"
    ]
  },
  "terminal-status": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-color-highlight, v3.0.8
autocomplete-plus, v2.9.0
color-picker, v1.6.0
file-icons, v1.5.4
language-arm, v0.3.2
language-aspx, v0.2.0
language-x86, v0.1.0
linter, v0.12.0
linter-bootlint, v0.0.5
linter-clang, v2.25.1
linter-csslint, v0.0.11
minimap, v4.7.6
open-last-project, v0.4.0
terminal-status, v1.6.3

# Dev
No dev packages
```

**Comment by pandres95** [comment]
Can you tell me if /Users/yanhan/.zlogin has read permissions for the user Atom is being executed?

**Comment by Tedko** [comment]
I just use chmod 777, but still cannot access it.

**Comment by pandres95** [comment]
Please try upgrading to `terminal-status@1.6.4` and tell me if your issue was solved.

**Comment by Tedko** [comment]
Just updated to 1.6.4, problem fixed.

Thx!
