### ISSUE TITLE
Failed to activate the terminal-status package

### ISSUE THREAD

**Issue by Tedko** [guileen/terminal-status#69]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.192.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [terminal-status](https://github.com/guileen/terminal-status) package, v1.6.5

### Stack Trace

Failed to activate the terminal-status package

```
At undefined is not a function

TypeError: undefined is not a function
  at Object.module.exports.activate (/Users/yanhan/.atom/packages/terminal-status/lib/cli-status.coffee:10:19)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:222:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:203:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:147:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:434:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -0:25.7 core:close (a.btn-issue.btn.btn-error)
     -0:12.8 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "color-gutter",
      "sublime-tabs",
      "vim-mode",
      "linter-htmlhint",
      "linter-cpplint"
    ]
  },
  "terminal-status": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-color-highlight, v3.0.8
autocomplete-plus, v2.11.0
color-picker, v1.7.0
file-icons, v1.5.4
language-arm, v0.3.3
language-aspx, v0.4.0
language-x86, v0.1.0
linter, v0.12.0
linter-bootlint, v0.0.5
linter-clang, v2.25.1
linter-csslint, v0.0.11
minimap, v4.7.6
open-last-project, v0.4.1
terminal-status, v1.6.5

# Dev
No dev packages
```

**Comment by pandres95** [comment]
We couldn't reproduce it. Please give us steps to know how we can find the error and I'll reopen the issue.
